### PR TITLE
[DON'T MERGE] Platform fortunes

### PR DESCRIPTION
**Pull request by sebastienros**
/cc @benaadams @davidfowl @DamianEdwards

### CODE REVIEW

**Comment by benaadams** [comment]
I assume have measured plaintext to ensure it hasn't been effected too much?

**Comment by sebastienros** [comment]
No, if you think it could be affected then I will measure.

**Comment by sebastienros** [comment]
Squashed and rebased on the new master

**Comment by benaadams** [comment]
Ah... nvm :)

**Pull request closed without merging**
